import type {NextPage} from 'next'
import Head from 'next/head'
import Image from '~/Image';
import profile from '../public/profile.jpg';
import Container from '~/Container';
import Section from '~/Section';
import Topic from '~/Topic';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container>
        <>
          <h1>FULL CYCLE SOFTWARE ENGINEER</h1>
          <h1>PASSION AND <b>EXPERIENCE</b></h1>
          <br/>
          <div className="row text-center">
            <div className="col">
              <Image image={profile}
                     alt="profile image"
                     type="image/jpg"
                     width={200}
                     rounded/>
              <br/>
              <br/>
              <h5>Dionisio Machado</h5>
              <p>User interface designer with a wealth of experience and a great passion in building new products and
                improving customer relationship during the design on New York - United States.</p>
            </div>
            <div className="col-md-8 d-flex flex-column align-items-end">
              <h2>EXPERIENCE</h2>
              <Section>
                <>
                  <Topic/>
                  <hr/>
                  <Topic/>
                </>
              </Section>

              <div className="row">
                <div className="col-md-6 d-flex flex-column align-items-end">
                  <h2>EDUCATION</h2>
                  <Section>
                    <>
                      <Topic/>
                      <hr/>
                      <Topic/>
                    </>
                  </Section>
                </div>

                <div className="col-md-6 d-flex flex-column align-items-end">
                  <h2>AWARDS</h2>
                  <Section>
                    <>
                      <Topic/>
                      <hr/>
                      <Topic/>
                    </>
                  </Section>
                </div>

                <div className="col-md-6 d-flex flex-column align-items-end">
                  <h2>SKILLS</h2>
                  <Section>
                    <>
                      <Topic/>
                      <hr/>
                      <Topic/>
                    </>
                  </Section>
                </div>
              </div>

            </div>
          </div>
        </>
      </Container>
    </>
  )
}

export default Home
